export const CARD_ATTRIBUTES = [
    "10th Anniversary Issue",
    "1st Edition",
    "60th Anniversary Issue",
    "65th Anniversary Issue",
    "Base Set",
    "Box Topper",
    "Chase",
    "Checklist",
    "Collectors Edition",
    "Digital",
    "Embossed",
    "Error Card",
    "Exchange/Redemption",
    "Exclusive",
    "Framed",
    "Hologram",
    "Insert",
    "Lenticular",
    "Limited Edition",
    "Memorabilia",
    "Mini",
    "Miscut",
    "Misprint",
    "One of One",
    "Parallel/Variety",
    "Printing Plate",
    "Promo",
    "Puzzle",
    "Rookie",
    "Sell Sheet",
    "Serial Numbered",
    "Short Print",
    "Sketch",
    "Stamped",
    "Sticker"
];

export const CARD_PARALLELS = [
    "150th Anniversary",
    "1st Day Issue",
    "23 Karat Gold",
    "25th Anniversary",
    "Acetate",
    "All-Black",
    "Amethyst",
    "Aqua",
    "Artist's Proof",
    "Asia Variations (Black, Blue, Gold, Red, etc.)",
    "Astro",
    "Atomic Refractor",
    "Black & White Variations",
    "Black Cracked Ice",
    "Black Finite",
    "Black Gold",
    "Black Mosaic",
    "Black Prizm",
    "Blue Cracked Ice",
    "Blue Foil",
    "Blue Ice",
    "Blue Prizm",
    "Bronze",
    "Camo",
    "Carolina Blue",
    "Checkerboard",
    "Choice Variations (Blue, Green, Red, Nebula, Tiger Stripe, etc.)",
    "Chrome & Chrome Refractors",
    "Cosmic",
    "Cracked Ice",
    "Crystal Variations",
    "Cubic",
    "Dazzle Variations",
    "Diamond & Diamond Anniversary",
    "Die-Cut",
    "Disco Prizm",
    "Electric Etch Variations (Blue, Green, Orange, Purple, Red, Yellow, etc.)",
    "Elephant",
    "Emerald",
    "Fast Break Variations (Blue, Bronze, Gold, Neon Green, etc.)",
    "Fire Burst",
    "Flash & Flash Prizm",
    "Foil & Foilboard",
    "FOTL (First Off The Line) Variations",
    "Fractal",
    "Galactic",
    "Glossy",
    "Gold & Gold Refractor Variations (Gold Vinyl, Gold Shimmer, etc.)",
    "Green & Green Refractor Variations (Green Ice, Green Pulsar, etc.)",
    "Groove",
    "High Gloss",
    "Holo & Holofoil Variations",
    "Hyper & Hyper Prizm",
    "Ice",
    "Image Variations",
    "Independence Day",
    "Infinite Variations",
    "Kaboom",
    "Lava",
    "Light Blue",
    "Lime Green",
    "Lucky Envelopes",
    "Magenta",
    "Marble",
    "Metal",
    "Mirror Variations (Gold, Green, Red, Blue, etc.)",
    "Mojo & Mojo Refractor",
    "Mosaic & Mosaic Prizm",
    "Nebula",
    "Neon Variations (Black Light, Blue, Green, Orange, etc.)",
    "Octagon Prizm",
    "On Fire",
    "OPC (O-Pee-Chee) Variations",
    "Orange & Orange Refractor",
    "Patch",
    "Pink Variations",
    "Platinum & Platinum Bar",
    "Power Prizm",
    "Precious Metal Gems (PMG)",
    "Press Proof Variations",
    "Printing Plate (Black, Cyan, Magenta, Yellow)",
    "Prism & Prizm",
    "Pulsar",
    "Purple & Purple Refractor Variations",
    "Rainbow & Rainbow Foil",
    "Rave",
    "RayWave Refractor",
    "Red & Red Refractor Variations (Red Wave, Red Ice, etc.)",
    "Red White & Blue Variations",
    "Refractor",
    "Ruby",
    "Sapphire",
    "Scope & Scope Prizm",
    "Shimmer & Shimmer Prizm",
    "Silver & Silver Prizm/Refractor",
    "Sparkle & White Sparkle",
    "Spectrum Variations",
    "SuperFractor",
    "Teal Variations",
    "Tie-Dye",
    "Tiffany",
    "Tiger",
    "UD Exclusives",
    "Vintage Stock",
    "Wave & Wave Prizm",
    "X-Fractor",
    "Yellow",
    "Young Guns",
    "Young Guns Canvas",
    "Zebra"
];
